#Définir les services app et db
services:
  app: 
     build: . #Créer une image à partir de Dockerfile courant 
     image: magasincrts
     entrypoint: project/entrypoint.sh
     restart: unless-stopped 
     ports: 
       - "7000:8000"
     depends_on: 
       - db
  db:
    image: postgres:15
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=ifnti
      - POSTGRES_DB=laraveldb
      - POSTGRES_PASSWORD=ifnti1234

volumes:
    dbdata:
