#Définir un nom
name: Laravel CI

#Définir les triggers
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 1- récuperer le code source 
            - name: Récupéré le code source
              uses: actions/checkout@v5
            
            # 2- Exécuter les tests

            - name: Run test
              run: cd app && php artisan serve